### ISSUE TITLE
org.apache.james:apache-mime4j:jar:0.8.0 can not be resolved

### ISSUE THREAD

**Issue by lutzhorn** [ram-sharma-6453/email-mime-parser#2]
The dependency on `org.apache.james:apache-mime4j:jar:0.8.0` can not be resolved to download the JAR ([see the search result](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.apache.james%22%20AND%20a%3A%22apache-mime4j%22%20AND%20v%3A%220.8.0%22)). Where is it available?

**Comment by ram-sharma-6453** [comment]
I looked into the issue and found the following:

1. For Gradle (2.10) based projects, the dependency of  `org.apache.james:apache-mime4j:jar:0.8.0` is getting resolved without an issue and the build succeeds.

2. For Maven (3.3.9) based projects, the dependency of `org.apache.james:apache-mime4j:jar:0.8.0` is not getting resolved totally and the build fails.

I am looking in to the matter for #2.
Reply me for which kind of projects you are unable to  download the dependency ?
Also try to validate my observations.

**Comment by lutzhorn** [comment]
Point 2 (Maven) is what I encounter, too. I will try to validate the Gradle build.

**Comment by ram-sharma-6453** [comment]
I am still investigating the maven issue, 

Till the time following alternative way of defining dependency in maven pom.xml for version 1.0.1 can keep you going:

```
        <dependency>
            <groupId>tech.blueglacier</groupId>
            <artifactId>email-mime-parser</artifactId>
            <version>1.0.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>apache-mime4j</artifactId>
                    <groupId>org.apache.james</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.james</groupId>
            <artifactId>apache-mime4j-core</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.james</groupId>
            <artifactId>apache-mime4j-dom</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.james</groupId>
            <artifactId>apache-mime4j-storage</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
        </dependency>
```

**Comment by ram-sharma-6453** [comment]
Update to version 1.0.2, fixed the issue.
