### ISSUE TITLE
mockito should be scope test

### ISSUE THREAD

**Issue by domdorn** [ram-sharma-6453/email-mime-parser#5]
Hi

mockito is currently in scope compile, this also pulls your specific version of mockito into my project. 
it should be made in scope test, so its available for your tests but does not get pulled into other projects that just use your library. 

thx

**Comment by ram-sharma-6453** [comment]
Apologies for the late reply, will fix and publish the update.

**Comment by ram-sharma-6453** [comment]
Apologies for the late fix.
