### ISSUE TITLE
Individual header maps

### ISSUE THREAD

**Issue by rahulm5000-r7** [ram-sharma-6453/email-mime-parser#6]
It looks like the .getHeader() method returns ALL header fields from all parts of the mail. is there a way to get only the fields from the parent part, or individual sub parts?

**Comment by ram-sharma-6453** [comment]
I am unable to understand the issue here, can you please explain by posting a relevant sample please.

**Comment by ram-sharma-6453** [comment]
Moreover if you have some requirement , or feature request , kindly elaborate with an example email, I will try to handle that.

**Comment by ram-sharma-6453** [comment]
Requested information not received, closing it.
