### ISSUE TITLE
Libraries shouldn't include slf4j implementations

### ISSUE THREAD

**Issue by hibikir** [ram-sharma-6453/email-mime-parser#8]
The gradle file includes slf4j-simple, which is a choice of which slf4j implementation to use. This might be necessary in tests (and just tests), but it will cause trouble to anyone using a different slf4j backend implementation: I've had to add a bonus exclusion for it, when it really isn't needed.

For a library, slf4j-api should be sufficient.

Would you mind removing the dependency? Would you accept a PR without it?

**Comment by ashiishsharma** [comment]
>> Would you mind removing the dependency? 
Will do that .
>> Would you accept a PR without it?
Sure

**Comment by ram-sharma-6453** [comment]
>> Would you mind removing the dependency? 
Will do that.

>> Would you accept a PR without it?
sure

**Comment by ram-sharma-6453** [comment]
Fixed.

**Comment by ram-sharma-6453** [comment]
Fixed in release v1.0.5
